name: Terraform and pfSense Automation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v2

      - name: List files in repository after checkout
        run: ls -la

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply \
          -var=host="${{ secrets.XEN_URL }}" \
          -var=username="${{ secrets.XEN_USERNAME }}" \
          -var=password='${{ secrets.XEN_PASSWORD }}' \
          -var-file="vars.tfvars" \
          -auto-approve \
          -lock=false

      - name: Capture Terraform Outputs and Save to File
        id: outputs
        run: |
          echo "Fetching Terraform Outputs..."
          echo "vm_mac_address=$(terraform output -raw vm_mac_address)" > vm_outputs.txt
          echo "new_vm_name=$(terraform output -raw new_vm_name)" >> vm_outputs.txt
          echo "template_name=$(terraform output -raw template_name)" >> vm_outputs.txt
          echo "memory=$(terraform output -raw memory)" >> vm_outputs.txt
          echo "cpus=$(terraform output -raw cpus)" >> vm_outputs.txt
          echo "disk_size=$(terraform output -raw disk_size)" >> vm_outputs.txt

      - name: List Environment Variables After Terraform Outputs
        run: |
          echo "VM MAC Address: ${{ env.vm_mac_address }}"
          echo "VM Name: ${{ env.new_vm_name }}"
          echo "Template Name: ${{ env.template_name }}"
          echo "Memory: ${{ env.memory }} MB"
          echo "CPUs: ${{ env.cpus }}"
          echo "Disk Size: ${{ env.disk_size }} GB"

  find_unused_ip:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v2

      - name: List files in repository after checkout
        run: ls -la

      - name: Setup Python virtual environment and install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install requests beautifulsoup4 ipaddress

      - name: Run get_unused_ip.py to find first available IP
        id: get_ip
        run: |
          source venv/bin/activate
          python3 ./.scripts/get_unused_ip.py \
          https://192.168.101.1/index.php \
          https://192.168.101.1/services_dhcp.php \
          ${{ secrets.PFSENSE_USERNAME }} \
          ${{ secrets.PFSENSE_PASSWORD }} > unused_ip.txt

      - name: Parse the first available IP
        id: parse_ip
        run: |
          AVAILABLE_IP=$(head -n 1 unused_ip.txt)
          echo "First available IP: $AVAILABLE_IP"
          echo "::set-output name=ip::$AVAILABLE_IP"

      - name: List IP from Parsing
        run: |
          echo "Parsed IP: ${{ steps.parse_ip.outputs.ip }}"

  register_in_pfsense:
    runs-on: self-hosted
    needs: find_unused_ip
    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v2

      - name: Setup Python virtual environment and install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install requests beautifulsoup4 ipaddress

      - name: Display vm_outputs.txt for Debugging
        run: |
          echo "Displaying contents of vm_outputs.txt..."
          cat vm_outputs.txt

      - name: Load VM Outputs from File
        run: |
          set -a  # automatycznie eksportuj zmienne
          source vm_outputs.txt
          set +a  # przestań eksportować zmienne
          echo "MAC Address: $vm_mac_address"
          echo "VM Name: $new_vm_name"
          echo "Template Name: $template_name"
          echo "Memory: $memory MB"
          echo "CPUs: $cpus"
          echo "Disk Size: $disk_size GB"

      - name: Register IP in pfSense
        run: |
          source venv/bin/activate
          python3 ./.scripts/register_in_pfsense.py \
          ${{ secrets.PFSENSE_USERNAME }} \
          ${{ secrets.PFSENSE_PASSWORD }} \
          $vm_mac_address \
          ${{ steps.parse_ip.outputs.ip }} \
          $new_vm_name \
          $template_name \
          $cpus \
          $memory \
          $disk_size

  summary:
    runs-on: self-hosted
    needs: register_in_pfsense
    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v2

      - name: Display VM summary
        run: |
          echo "VM Details:"
          echo "Hostname: $new_vm_name"
          echo "IP Address: ${{ steps.parse_ip.outputs.ip }}"
          echo "MAC Address: $vm_mac_address"
          echo "CPU(s): $cpus"
          echo "Memory: $memory MB"
          echo "Disk Size: $disk_size GB"
