name: Terraform Deployment on Self-Hosted Runner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan \
          -var="host=${{ secrets.XEN_URL }}" \
          -var="username=${{ secrets.XEN_USERNAME }}" \
          -var="password=${{ secrets.XEN_PASSWORD }}" \
          -var-file="vars.tfvars" \
          -out=tfplan

      - name: Save Terraform Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: ./tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: |
          terraform apply \
          -var="host=${{ secrets.XEN_URL }}" \
          -var="username=${{ secrets.XEN_USERNAME }}" \
          -var="password=${{ secrets.XEN_PASSWORD }}" \
          -var-file="vars.tfvars" \
          -auto-approve

      - name: Save Terraform State
        uses: actions/upload-artifact@v3
        with:
          name: terraform-state
          path: ./terraform.tfstate
