name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan \
          -var="host=${{ secrets.XEN_URL }}" \
          -var="username=${{ secrets.XEN_USERNAME }}" \
          -var="password=${{ secrets.XEN_PASSWORD }}" \
          -var-file="vars.tfvars"

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply \
          -var="host=${{ secrets.XEN_URL }}" \
          -var="username=${{ secrets.XEN_USERNAME }}" \
          -var="password=${{ secrets.XEN_PASSWORD }}" \
          -var-file="vars.tfvars" \
          -auto-approve
